### ISSUE TITLE
-threads flag question

### ISSUE THREAD

**Issue by BilboBaggenses** [ncabatoff/process-exporter#152] opened 2020-06-10 21:13 UTC
Thank you for writing this useful tool.  Getting some great value out of it.  However, our Prometheus admin is asking us to try and limit the number of metrics we're collecting that we are not using. 

I noticed that there's a flag called -threads, it defaults to true.  Would like to turn them off.  

I was running the process with these args and was still getting the thread metrics:
```
./process-exporter -debug -config.path process-exporter.yml -threads false

namedprocess_namegroup_thread_cpu_seconds_total{groupname="XXXXXCFSensor-AN01",mode="system",threadname="XXXXX"} 0

```

**Comment by rajarameshyv** [comment] 2020-08-31 23:42
I am also seeing same issue. Did anyone find fix already? 
/opt/monitoringpack/bin/process-exporter -web.listen-address 127.0.0.1:10081 -config.path /etc/monitoringpack/process-exporter.yaml -threads false

namedprocess_namegroup_thread_minor_page_faults_total{groupname="mongod",threadname="listener"} 6
namedprocess_namegroup_thread_minor_page_faults_total{groupname="mongod",threadname="mongod"} 454

**Comment by singhjagmohan1000** [comment] 2020-09-01 15:50
@BilboBaggenses try `-threads=false`. I think what you are missing here is `=`.

**Comment by niamR** [comment] 2020-11-25 19:44
Worked fine for me once provided the -threads false option before the -config.path
As written in the README, usage is : 
process-exporter [options] -config.path filename.yml

**Comment by ncabatoff** [comment] 2021-10-17 17:23
It's not the ordering of options as @niamR suggests, the issue is that boolean flags require an equals sign.  So `-threads false` doesn't work, but `-threads=false` does.  Closing because I can't reproduce the issue when using an equals sign.

**Closed by ncabatoff** 2021-10-17 17:23 UTC
